Add json and json-pretty output options
sindresorhus/fast-cli pull request #56
Opened 2021-01-05 01:38 UTC by seanmcne

output examples: 
for json human readable output
```
node .\cli.js --json-pretty -u
{
     "downloadSpeed": 29,
     "downloadUnit": "Mbps",
     "downloadedMb": 30,
     "uploadSpeed": 13,
     "uploadUnit": "Mbps",
     "uploadedMb": 40,
     "latency": 44,
     "bufferBloat": 75,
     "userLocation": "Chicago, US",
     "userIp": "1.2.3.4",
     "isDone": true
}
for json only output 
```
node .\cli.js --json -u        
{"downloadSpeed":32,"downloadUnit":"Mbps","downloadedMb":80,"uploadSpeed":10,"uploadUnit":"Mbps","uploadedMb":30,"latency":52,"bufferBloat":75,"userLocation":"Chicago, US","userIp":"1.2.3.4","isDone":true}
```

```

2021-01-05 03:27 UTC, sindresorhus commented
I don't see the point of 2 JSON flags. Make it just `--json` and pretty.

2021-01-05 04:58 UTC, seanmcne commented
> I don't see the point of 2 JSON flags. Make it just `--json` and pretty.

I assume there are some folks that want to use this in automation and logging and wouldn't want the extra spaces and tabs, whereas some may want it human readable (it's actually matching the options that speedtest.net has for their CLI).

2021-01-06 06:27 UTC, sindresorhus commented
> I assume there are some folks that want to use this in automation and logging and wouldn't want the extra spaces and tabs, whereas some may want it human-readable (it's actually matching the options that speedtest.net has for their CLI).

Logging is a good point. Let's only do the one-line version then. I don't really see the point of human-readable JSON output anyway, as we already have a nice output for humans. If someone needs a nice JSON output they can pipe the output through some JSON formatter.

2021-01-06 06:28 UTC, sindresorhus commented
> My previous experience with a similar command line tool was for speedtest-cli - here is the command help output for that cli tool which is what I patterned json and json-pretty from:

I prefer to keep my CLIs minimal.

2021-01-06 20:43 UTC, seanmcne commented
> > I assume there are some folks that want to use this in automation and logging and wouldn't want the extra spaces and tabs, whereas some may want it human-readable (it's actually matching the options that speedtest.net has for their CLI).
> 
> Logging is a good point. Let's only do the one-line version then. I don't really see the point of human-readable JSON output anyway, as we already have a nice output for humans. If someone needs a nice JSON output they can pipe the output through some JSON formatter.

Sounds good - I just adjusted cli.js.  Let me know what you thank - thx!

2021-01-07 06:29 UTC, sindresorhus requested changes

2021-01-07 06:29 UTC, sindresorhus commented on cli.js
> +		logUpdate(JSON.stringify(data, null, null));
```suggestion
		logUpdate(JSON.stringify(data));
```

2021-01-07 06:29 UTC, sindresorhus commented on cli.js
> +const spacing = amount => (cli.flags.singleLine || cli.flags.json || cli.flags.jsonPretty ? '' : ' '.repeat(amount));
Outdated code

2021-01-07 06:29 UTC, sindresorhus commented on cli.js
> +	  --json         Process output in json format also forces single line
```suggestion
	  --json         JSON output
```

You also need to update the readme.

2021-01-07 06:29 UTC, sindresorhus commented on cli.js
> +	  $ fast --upload --json-pretty
Outdated

2021-01-07 06:31 UTC, sindresorhus commented
@seanmcne I would recommend looking over your own diff after doing changes. I think you could have caught some of the things I commented yourself. 👍🏻

2021-05-07 18:37 UTC, sindresorhus commented
Closing in favor of #58

2021-05-07 18:37 UTC, closed without merging